### ISSUE TITLE
Latest sslib updated to the worker isn't compatible

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#118]
### Describe the bug

See the functional test https://github.com/vmware/repository-service-tuf/actions/runs/3329935767/jobs/5507780019

Commit mentioned: https://github.com/vmware/repository-service-tuf-worker/commit/8ef18e26438118c1d8c6c624ae8b19c85ac00574

https://github.com/vmware/repository-service-tuf-worker/blob/ab37ddf8259f92ebb4eaf463d1cc4822bc910d56/requirements.txt#L27

```shell
epository-service-tuf-worker_1  | [2022-10-27 06:49:53,664: ERROR/ForkPoolWorker-8] Task app.repository_service_tuf_worker[74bb50defe804099adde7b7dd0759080] raised unexpected: TypeError("LocalStorage.put() got an unexpected keyword argument 'restrict'")
repository-service-tuf-worker_1  | Traceback (most recent call last):
repository-service-tuf-worker_1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
repository-service-tuf-worker_1  |     R = retval = fun(*args, **kwargs)
repository-service-tuf-worker_1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
repository-service-tuf-worker_1  |     return self.run(*args, **kwargs)
repository-service-tuf-worker_1  |   File "/opt/repository-service-tuf-worker/app.py", line 75, in repository_service_tuf_worker
repository-service-tuf-worker_1  |     result = repository_action(payload, update_state=self.update_state)
repository-service-tuf-worker_1  |   File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/repository.py", line 384, in bootstrap
repository-service-tuf-worker_1  |     metadata.to_file(
repository-service-tuf-worker_1  |   File "/usr/local/lib/python3.10/site-packages/tuf/api/metadata.py", line 339, in to_file
repository-service-tuf-worker_1  |     persist_temp_file(temp_file, filename, storage_backend)
repository-service-tuf-worker_1  |   File "/usr/local/lib/python3.10/site-packages/securesystemslib/util.py", line 222, in persist_temp_file
repository-service-tuf-worker_1  |     storage_backend.put(temp_file, persist_path, restrict=restrict)
repository-service-tuf-worker_1  | TypeError: LocalStorage.put() got an unexpected keyword argument 'restrict'
```
### Reproduction steps

1. Update securesystemslib 
1. Deploy the 'dev' tag containers
2. Use the latest CLI version 
3. Perform the Ceremony
4. Bootstrap the RSTUF

### Expected behavior

Compatible with the latest securesystemslib

### Additional context

The Functional test needs to run for bumping the dependencies (#116)
 - #116

Or before release (https://github.com/vmware/repository-service-tuf-worker/issues/117)

- https://github.com/vmware/repository-service-tuf-worker/issues/117

**Comment by kairoaraujo** [comment]
PR #119 doesn't close this bug, it is only a workaround for [`v0.0.1a2`](https://github.com/vmware/repository-service-tuf-worker/releases/tag/v0.0.1a2) (possible `v0.0.1a2-1`)
- #119
