### ISSUE TITLE
Bug: [roles simplification] Adding a target is not working

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#232]
### What happened?

Adding a target is not working.

**Note**: Fixing it also is good to test removing targets.

### What steps did you take?

1. Deploy the environment or use the development environment with the `feature/roles-simplification` branch.
2. Run the bootstrap
3. Add a target

### Relevant log output

```shell
[2023-03-23 10:02:20,664: ERROR/ForkPoolWorker-8] Task app.repository_service_tuf_worker[d4894c26a3754cfda750adeda4d3496e] raised unexpected: StorageError("Can't open Role 'targets'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tuf/api/serialization/json.py", line 36, in deserialize
    json_dict = json.loads(raw_data.decode("utf-8"))
AttributeError: '_io.BufferedReader' object has no attribute 'decode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/services/storage/local.py", line 63, in get
    return Metadata.from_bytes(file_object)
  File "/usr/local/lib/python3.10/site-packages/tuf/api/metadata.py", line 264, in from_bytes
    return deserializer.deserialize(data)
  File "/usr/local/lib/python3.10/site-packages/tuf/api/serialization/json.py", line 40, in deserialize
    raise DeserializationError("Failed to deserialize JSON") from e
tuf.api.serialization.DeserializationError: Failed to deserialize JSON

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/repository-service-tuf-worker/app.py", line 88, in repository_service_tuf_worker
    result = repository_action(payload, update_state=self.update_state)
  File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/repository.py", line 511, in add_targets
    bins_name = self._get_path_succinct_role(target["path"])
  File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/repository.py", line 323, in _get_path_succinct_role
    bin_role = self._load(Targets.type)
  File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/repository.py", line 217, in _load
    return Metadata.from_file(role_name, None, self._storage_backend)
  File "/usr/local/lib/python3.10/site-packages/tuf/api/metadata.py", line 233, in from_file
    with storage_backend.get(filename) as file_obj:
  File "/opt/repository-service-tuf-worker/repository_service_tuf_worker/services/storage/local.py", line 65, in get
    raise StorageError(f"Can't open Role '{role}'") from e
securesystemslib.exceptions.StorageError: Can't open Role 'targets'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
It is fixed in branch feature/roles-simplification.
